[package]
name = "gravity"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.0"
actix-web = "4.0.1"
actix-web-actors = "4.1.0"
tera = "1.15.0"
once_cell = "1.10.0"
slog = "2.7.0"
sloggers = "2.1.1"
clap = { version = "3.1.18" , features = ["derive"] }
