steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/hoprassociation/playground
      - --cache=true
      - --cache-ttl=96h
    timeout: 2400s
options:
  logStreamingOption: STREAM_ON
  substitutionOption: MUST_MATCH
  machineType: E2_HIGHCPU_8
